DOCSP-42666: serialization
mongodb/docs-kotlin-sync pull request #39
Opened 2024-08-20 15:04 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-kotlin-sync/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-42666>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin-sync/DOCSP-42666-serialization/data-formats/serialization/

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-08-20 15:37 UTC, mcmorisi approved these changes
LGTM with some tiny nits!

2024-08-20 15:37 UTC, mcmorisi commented on source/data-formats/serialization.txt
> +``kotlinx.serialization`` to serialize and deserialize data in your
```suggestion
``kotlinx.serialization``, to serialize and deserialize data in your
```

2024-08-20 15:37 UTC, mcmorisi commented on source/data-formats/serialization.txt
> +Then, you can define your codec by using the `KotlinSerializerCodec.create()
```suggestion
You can define your codec by using the `KotlinSerializerCodec.create()
```

2024-08-20 15:37 UTC, mcmorisi commented on source/data-formats/serialization.txt
> +method and add it to the registry.
```suggestion
method and adding it to the registry.
```

2024-08-20 15:37 UTC, mcmorisi commented on source/includes/data-formats/serialization.kt
> +    val resultStudent =collection.withDocumentClass<Student>()
```suggestion
    val resultStudent = collection.withDocumentClass<Student>()
```

2024-08-21 09:05 UTC, rozza requested changes
Recommend using the https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/fundamentals/data-formats/serialization/ page wholesale.

Its important to have the differentiation between kotlinx serialization and using codecs. Which appears to be missing from this page.

2024-08-21 19:30 UTC, merged